import { newUnavail } from './constants';

export const SEED_EMPLOYEES = [
  {
    id:"sl-1",name:"Chan In",role:"shift_lead",status:"active",
    maxShifts:4,minShifts:4,maxHours:24,minHours:18,
    tags:["can_swirl","can_mc","good_weekend","mc_rotation_sun","day_lead_eligible"],
    unavailability:newUnavail(),
    notes:"Fully available all week.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"sl-2",name:"Zoe Rains",role:"shift_lead",status:"active",
    maxShifts:4,minShifts:4,maxHours:24,minHours:18,
    tags:["can_swirl","can_mc","mc_rotation_thu","day_lead_eligible"],
    unavailability:{
      mon:{allDay:false,start:"09:00",end:"15:00"},
      tue:{allDay:true,start:"",end:""},
      wed:{allDay:false,start:"09:00",end:"15:00"},
      thu:{allDay:false,start:"11:00",end:"16:00"},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"Always MCs Thursday with Crystal.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"sl-3",name:"Kaitlyn Trevino",role:"shift_lead",status:"active",
    maxShifts:4,minShifts:4,maxHours:24,minHours:18,
    tags:["can_swirl","can_mc","good_weekend","mc_rotation_sun","day_lead_eligible"],
    unavailability:{
      ...newUnavail(),
      wed:{allDay:false,start:"19:00",end:"22:30"},
    },
    notes:"Only restriction: Wed 7pm-10:30pm.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"sl-4",name:"Spencer Losch",role:"shift_lead",status:"active",
    maxShifts:4,minShifts:4,maxHours:24,minHours:18,
    tags:["can_swirl","can_mc","good_weekend","mc_rotation_sun","day_lead_eligible"],
    unavailability:newUnavail(),
    notes:"Fully available all week.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"sl-5",name:"Crystal Guel",role:"shift_lead",status:"active",
    maxShifts:4,minShifts:4,maxHours:24,minHours:18,
    tags:["can_swirl","can_mc","mc_rotation_thu","day_lead_eligible"],
    unavailability:{
      mon:{allDay:false,start:"",end:""},
      tue:{allDay:false,start:"09:00",end:"12:30"},
      wed:{allDay:false,start:"",end:""},
      thu:{allDay:false,start:"09:00",end:"12:30"},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:true,start:"",end:""},
    },
    notes:"Always MCs Thursday (Sun all day off).",traineeCumulative:0,guaranteedDays:["fri","sat"],
  },
  {
    id:"reg-1",name:"Kennedy Bean",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_swirl","good_weekend","can_mc"],
    unavailability:{
      mon:{allDay:false,start:"09:00",end:"15:00"},
      tue:{allDay:false,start:"",end:""},
      wed:{allDay:false,start:"09:00",end:"15:00"},
      thu:{allDay:false,start:"",end:""},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"Good person. Can do 4 shifts.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-2",name:"Sam Castillo",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_swirl","fourth_shift_priority","can_mc"],
    unavailability:{
      mon:{allDay:true,start:"",end:""},
      tue:{allDay:false,start:"",end:""},
      wed:{allDay:true,start:"",end:""},
      thu:{allDay:false,start:"",end:""},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"Mon & Wed all day off. 4th shift priority.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-3",name:"Lena Maslak",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_swirl","fourth_shift_priority","second_day_priority","can_mc"],
    unavailability:{
      mon:{allDay:false,start:"11:00",end:"13:00"},
      tue:{allDay:false,start:"08:00",end:"12:00"},
      wed:{allDay:false,start:"11:00",end:"13:00"},
      thu:{allDay:false,start:"08:00",end:"12:00"},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"2nd Day & 4th shift priority. Tue/Thu can start at 12pm. Fri-Sun clear.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-4",name:"Gwen Ursua",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_swirl","good_weekend","can_mc"],
    unavailability:{
      ...newUnavail(),
      sun:{allDay:false,start:"09:00",end:"18:00"},
    },
    notes:"Good person. Can do 4 shifts. Sun unavailable 9am-6pm.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-5",name:"Susan Thai",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_swirl","fourth_shift_priority","can_mc"],
    unavailability:{
      mon:{allDay:false,start:"",end:""},
      tue:{allDay:false,start:"08:00",end:"15:30"},
      wed:{allDay:false,start:"",end:""},
      thu:{allDay:false,start:"08:00",end:"15:30"},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"Can do Thu MC (6pm+). 4th shift priority. Fri-Sun clear.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-6",name:"Abrar Uddin",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_swirl","fourth_shift_priority","second_day_priority","good_weekend","no_weekday_nights"],
    unavailability:{
      mon:{allDay:false,start:"",end:""},
      tue:{allDay:true,start:"",end:""},
      wed:{allDay:false,start:"",end:""},
      thu:{allDay:true,start:"",end:""},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"Tue & Thu all day off. No weekday nights. Weekend nights OK.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-7",name:"Grae McKown",role:"regular",status:"active",
    maxShifts:2,minShifts:2,maxHours:12,minHours:8,
    tags:["good_weekend"],
    unavailability:{
      mon:{allDay:true,start:"",end:""},
      tue:{allDay:false,start:"06:00",end:"15:00"},
      wed:{allDay:false,start:"06:00",end:"15:00"},
      thu:{allDay:false,start:"06:00",end:"15:00"},
      fri:{allDay:false,start:"06:00",end:"15:00"},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"2 shifts max. Mon off. Tue-Fri evenings only. Sat/Sun available.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"reg-8",name:"Christina Mullins",role:"regular",status:"active",
    maxShifts:4,minShifts:3,maxHours:20,minHours:12,
    tags:["can_mc"],
    unavailability:{
      mon:{allDay:false,start:"09:00",end:"15:00"},
      tue:{allDay:false,start:"09:00",end:"15:00"},
      wed:{allDay:false,start:"09:00",end:"15:00"},
      thu:{allDay:false,start:"09:00",end:"15:00"},
      fri:{allDay:false,start:"",end:""},
      sat:{allDay:false,start:"",end:""},
      sun:{allDay:false,start:"",end:""},
    },
    notes:"Mon-Thu unavailable 9am-3pm. Gets 4th shift after Sam/Lena/Susan/Abrar.",traineeCumulative:0,guaranteedDays:[],
  },
  {
    id:"tr-1",name:"Yise Moya",role:"trainee",status:"active",
    maxShifts:3,minShifts:1,maxHours:15,minHours:0,
    tags:[],unavailability:newUnavail(),
    notes:"Fully available.",traineeCumulative:8.0,guaranteedDays:[],
  },
  {
    id:"tr-2",name:"Tiernan Hollister",role:"trainee",status:"active",
    maxShifts:3,minShifts:1,maxHours:15,minHours:0,
    tags:[],unavailability:newUnavail(),
    notes:"Fully available.",traineeCumulative:10.0,guaranteedDays:[],
  },
];

export const SEED_RULES = {
  constraints: [
    {id:"no_doubles",label:"No doubles",desc:"No employee works two shifts in one day",enabled:true},
    {id:"no_day_after_mc",label:"No day shift after MC night",desc:"Employee who MCs at night cannot work day shift next day. Evening/night next day is OK.",enabled:true},
    {id:"no_fri_sat_night",label:"No Fri + Sat night same person",desc:"Cannot schedule same employee for both Friday and Saturday night shifts",enabled:true},
    {id:"no_sat_sun_night",label:"No Sat + Sun night same person",desc:"Cannot schedule same employee for both Saturday and Sunday night shifts",enabled:true},
    {id:"sat_night_sl_neq_sun_sl",label:"Sat night SL \u2260 Sun SL/MC",desc:"Saturday night Shift Lead must be different from Sunday Shift Lead / MC leader",enabled:true},
    {id:"only_sl_lead",label:"Only SLs can be DL or evening SL",desc:"Day Lead and evening Shift Lead roles are restricted to Shift Leads",enabled:true},
    {id:"overlap_blocks",label:"Any unavailability overlap blocks shift",desc:"If any part of a shift overlaps with an employee's unavailability, they cannot work that shift",enabled:true},
    {id:"no_trainees_mc",label:"No trainees on MC nights",desc:"Trainees cannot be assigned to machine cleaning shifts",enabled:true},
    {id:"mc_evening_sl_leads",label:"Evening SL leads MC",desc:"The Evening SL on MC night IS the MC leader. MC crew = Evening SL + 1 SL helper + 2 regulars (4 total).",enabled:true},
    {id:"no_two_trainees",label:"No two trainees on same day",desc:"Avoid scheduling two trainees on the same day to ensure proper supervision",enabled:true},
    {id:"no_mc_twice",label:"No MC more than once per week",desc:"No employee can be assigned to machine cleaning more than once per week",enabled:true},
    {id:"no_trainees_weekday_day",label:"No trainees on weekday day shifts",desc:"Trainees cannot work Mon-Fri day shifts (Day Lead or 2nd Day)",enabled:true},
    {id:"no_fri_sat_sun",label:"No Fri + Sat + Sun same person",desc:"Cannot schedule same employee for all 3 weekend days (Friday, Saturday, Sunday). Max 2 of 3.",enabled:true},
    {id:"max_consecutive_3",label:"Max 3 consecutive work days",desc:"Avoid scheduling an employee more than 3 days in a row to prevent burnout.",enabled:true},
    {id:"min_swirlers_weekend",label:"Min 2 swirlers per weekend shift",desc:"Friday night through Sunday must have at least 2 employees who can swirl (make soft serve) per shift period.",enabled:true},
  ],
  shiftLead: { shiftsPerWeek:{min:4,max:4}, minWeekendShifts:2, mcPerWeek:1, alternateDayLeads:true },
  regular: { shiftsPerWeek:{min:3,max:4} },
  trainee: { shiftsPerWeek:{min:0,max:3}, graduationHours:30, fillGapsOnly:true, doNotReplaceRegulars:true },
  staffing: {
    weekday:{day:2,evening:3,total:5},
    weekdayHoliday:{day:3,evening:4,total:7},
    friday:{day:2,evening:4,total:6},
    fridayHoliday:{day:3,evening:4,total:7},
    saturday:{day:3,mid:1,evening:4,total:8},
    sunday:{day:3,mid:1,evening:4,total:8},
  },
  shiftTimes: {
    weekdayDay:{start:"12:00",end:"18:00"},
    weekdayEvening:{start:"18:00",end:"22:30"},
    weekdayEveningStagedArrivals:["18:00","18:00","18:15"],
    weekdayHolidayEveningStagedArrivals:["18:00","18:00","18:15","18:30"],
    fridayDay:{start:"11:30",end:"18:00"},
    fridayHolidayDay:{start:"11:30",end:"18:00"},
    weekendDay:{start:"11:30",end:"18:00"},
    weekendEvening:{start:"18:00",end:"23:30"},
    weekendEveningStagedArrivals:["18:00","18:00","18:15","18:30"],
    satMid:{start:"15:00",end:"19:00"},
    mcNight:{start:"18:00",end:"23:45"},
    mcStagedArrivals:["18:00","18:00","18:15"],
    mcHolidayStagedArrivals:["18:00","18:00","18:15","18:30"],
    weekdayClose:"22:30",weekendClose:"23:30",mcClose:"23:45",
  },
  fourthShiftPriority:["Sam Castillo","Lena Maslak","Susan Thai","Abrar Uddin","Christina Mullins","Trainees"],
  secondDayPriority:["Lena Maslak","Abrar Uddin"],
  goodWeekendPeople:["Kennedy Bean","Gwen Ursua","Abrar Uddin","Grae McKown"],
  swirl:{
    minPerShift: 2,
    weekendOnly: true,
    swirlers: ["Chan In","Zoe Rains","Kaitlyn Trevino","Spencer Losch","Crystal Guel","Kennedy Bean","Sam Castillo","Lena Maslak","Gwen Ursua","Susan Thai","Abrar Uddin"],
  },
  fixedRules: [
    {id:"fr-1",empName:"Crystal Guel",rule:"Always MCs Thursday",desc:"Crystal is off Sundays, so she must MC on Thursday every week"},
    {id:"fr-2",empName:"Zoe Rains",rule:"Always MCs Thursday",desc:"Zoe is paired with Crystal for Thursday MC"},
    {id:"fr-3",empName:"Grae McKown",rule:"Max 2 shifts per week",desc:"Grae limited to 2 shifts maximum"},
  ],
  mcRotation: {
    shiftLeadPool:["Chan In","Zoe Rains","Kaitlyn Trevino","Spencer Losch","Crystal Guel"],
    assistantPool:["Sam Castillo","Lena Maslak","Gwen Ursua","Susan Thai","Abrar Uddin","Kennedy Bean","Christina Mullins"],
    noBackToBackHelpers:true,
  },
  weekendSLRotation: {
    fridayNightPool:["Chan In","Spencer Losch","Crystal Guel","Zoe Rains","Kaitlyn Trevino"],
    saturdayNightPool:["Chan In","Spencer Losch","Crystal Guel","Kaitlyn Trevino"],
    saturdayDayPool:["Chan In","Spencer Losch","Crystal Guel","Kaitlyn Trevino"],
  },
  secondDay: { alternateDifferentPersonEachDay:true, startsAt:"12:00", mustBeAvailableAtStart:true },
  slShortWeekHistory: [],
};
